# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
