# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160709_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=50),
        ),
    ]
