# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160710_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItems',
            new_name='Items',
        ),
    ]
